use INVOIC;
create user user1@'localhost' identified by 'user1';
create user user2@'localhost' identified by 'user2';
grant insert,select on INVOIC.CUSTOMER to user1@'localhost';
show grants for user1@'localhost';
grant update,delete on INVOIC.* to user2@'localhost';
show grants for user2@'localhost';
revoke delete on INVOIC.* from user2@'localhost';
create database SCHOOL;
use SCHOOL;
create table student(id int primary key auto_increment,name varchar(20),department varchar(30));
desc student;
use SCHOOL;
insert into student values(1,'abhi','mca');
insert into student values(2,'nayana','mca');
insert into student values(3,'anu','mca');
insert into student values(4,'ammu','mba');
insert into student values(5,'raga','mba');
commit;
select * from student;
insert into student values(6,'anju','bca');
rollback;
insert into student values(7,'appu','bca');
savepoint t1;
insert into student values(8,'varun','bca');
select * from student;
rollback;
select * from student;

